### PR TITLE
Fixed exception when removing player from cooldown list

### PR DESCRIPTION
**Pull request by Gluton-Official**

### CODE REVIEW

**Comment by SilverAndro** [comment]
Unable to reproduce issue in dev

**Comment by Fourmisain** [comment]
[Disclaimer: This is a comment, code review and code change request all at once]

This is really easy to reproduce independently (by replacing `ServerPlayerEntity` and the remove condition):
```
HashMap<Integer, Integer> cooldowns = new HashMap<>();

cooldowns.put(1, 1);
cooldowns.put(2, 2);
cooldowns.put(3, 3);

for (Integer player : cooldowns.keySet()) {
	int current = cooldowns.get(player);
	if (current == 2) {
		cooldowns.remove(player);
	}
}
```
will throw a `ConcurrentModificationException` and the same can happen with the live code too.

You should (generally) never modify a collection while iterating over it - or to be more precise, only the `Iterator` used for iteration (`:` for-each uses one behind the scenes) is able to (safely) modify the collection.

So one approach would be to write:
```
Iterator<ServerPlayerEntity> it = cooldowns.keySet().iterator();
while (it.hasNext()) {
	ServerPlayerEntity player = it.next();
	if (cooldowns.get(player) <= 0) {
		it.remove();
	}
}
```

This PR also fixes the issue, but it is also unnecessarily creating a temporary list and uses `Lists.newArrayList();` which adds a Guava dependency and that should have been `new ArrayList<>();` instead.

A much simpler and more elegant solution is to write the one-liner:
```
cooldowns.keySet().removeIf(player -> cooldowns.get(player) <= 0);
```

And even with that there's a small nitpick:
Iterating over the keys and using `get` to get the value is inefficient and it's better to use the `entrySet()` instead.
Applying that would looks like:
```
cooldowns.entrySet().removeIf(entry -> entry.getValue() <= 0);
```
which is admittedly a little worse to read, but that's what comments are for.

---

Also, about the code right above the removal:
```
for (ServerPlayerEntity player : cooldowns.keySet()) {
    int current = cooldowns.get(player);
    cooldowns.put(player, current - 1);
}
```
while it is correct (the `put` uses only the keys that are already in the `keySet()`, therefore the map it not actually modified), it too can be simplified to a one-liner:
```
cooldowns.replaceAll((player, cooldown) -> cooldown - 1);
```

---

So putting everything together, I'd suggest changing the event to this:
```
        ServerTickEvents.END_SERVER_TICK.register((world) -> {
            cooldowns.replaceAll((player, cooldown) -> cooldown - 1);
            cooldowns.entrySet().removeIf(entry -> entry.getValue() <= 0);
        });
```

**Comment by SilverAndro** [comment]
Im well aware of the possibilities for ConcurrentModificationException, I deal with them regularly, and if they were throw in this case I wouldn't have released a version with the existing code

This is the master branch code, running on a dedicated server from a dev environment

https://user-images.githubusercontent.com/52360088/110408168-0d757180-807d-11eb-9306-43448c62a271.mp4

As you can see, the cooldown successfully completes with no crashes

If a crash report can be provided proving that this a legitimate issue then I will merge this (or fix this, given the concerns you raised given the code quality)

**Comment by Fourmisain** [comment]
Sorry, but of course this won't crash when your collection only has 1 element in it, since the `Iterator.hasNext()` would return `false` immediately after the first `next()`. Think of `next()` as `i++` and `hasNext()` as `i < length`.
This mean a second `next()` is never called and therefore an exception can never be thrown.

Don't you think @Gluton-Official _wouldn't_ have reported this if it wouldn't happen?

**Comment by Gluton-Official** [comment]
This is the crash report. Yes, it will not occur with only one element in the map.

[crash-2021-02-03_00.18.25-server.txt](https://github.com/P03W/itemflexer/files/6105445/crash-2021-02-03_00.18.25-server.txt)

**Comment by SilverAndro** [comment]
Ok. ill fix this

RE: "Don't you think Gluton-Official wouldn't have reported this if it wouldn't happen?"

Given they 
1. Didnt open an issue
2. Didnt reply when I said I couldn't reproduce this
3. Didnt provide a crash report initially

I saw no reason to trust the PR as a legitimate issue

**Comment by Gluton-Official** [comment]
1/2. I did a pull request because I'm able to build the mod with my fix quicker than waiting for the issue to be solved
3. I didn't think a crash report was needed since I already located the problem in your code.

Thank you @Fourmisain for explaining the issue and the improvements!

**Pull request closed without merging**
