### PR TITLE
Update to 1.19

### PR DESCRIPTION
**Pull request by soqb**
updated to `fabric-command-api-v2` and to `eu.pb4:placeholder-api:2.0.0-beta.5+1.19` along with the required changes to mappings and code.

also added `.vscode/` to the gitignore since that's the editor i use.

### CODE REVIEW

**Comment by SilverAndro** [comment]
I appreciate this but I'm not a fan of the styling changes 😅 I usually keep stuff visually organized like that for a reason, haha

**Comment by soqb** [comment]
@SilverAndro i'm not exactly sure what you mean; `placeholder-api` and `fabric-command-api` were both updated (`2.0.0` and `v2` respectively) to change their syntax slightly, and 1.19 removed `LiteralText` as far as i know, this PR is the minimal set of required changes.

(edit: forgot to mention that `fabric-command-api-v1` is not supported in 1.19 and `placeholder-api` does not have a legacy version available)

**Comment by soqb** [comment]
just understood what you meant by style changes; i had no idea vscode had reformatted that file. should have reverted the formatting changes in the most recent commit.

**Comment by SilverAndro** [comment]
Awesome, thanks much!

Sorry I didn't properly point out the style changes, was in a bit of a rush yesterday 😅

I'll merge this now and get a release out later

**Pull request merged**
